services:
  dev:
    image: dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - ROS_DISTRO=foxy
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}
      target: dev
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: True
    environment:
      - DISPLAY=${DISPLAY:-unix:0}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UID=${UID:-1000}
      - GID=${UID:-1000}
      - USERNAME=${USERNAME:-devuser}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ./PX4-Autopilot:/home/${USERNAME:-devuser}/PX4-Autopilot:rw
      - ./ros2_ws:/home/${USERNAME:-devuser}/ros2_ws:rw
      # Mount the source code
      # - ./my_package:/overlay_ws/src/my_package:rw
      # # Mount colcon build artifacts for faster rebuilds
      # - ./.colcon/build/:/overlay_ws/build/:rw
      # - ./.colcon/install/:/overlay_ws/install/:rw
      # - ./.colcon/log/:/overlay_ws/log/:rw
    user: ${USERNAME:-devuser}
    command: sleep infinity
